# Generated by Django 4.2.16 on 2026-09-28 11:22

import apps.account.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('nickname', models.CharField(blank=True, max_length=64, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, verbose_name='头像URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最近登录IP')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'account_user',
            },
            managers=[
                ('objects', apps.account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_chapter', models.IntegerField(default=0, verbose_name='最后阅读章节')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='最后阅读时间')),
            ],
            options={
                'verbose_name': '书架',
                'verbose_name_plural': '书架',
                'db_table': 'account_bookshelf',
                'ordering': ('-added_at',),
            },
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP')),
                ('label', models.CharField(blank=True, help_text='如：办公室', max_length=64, verbose_name='标签')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IP 白名单',
                'verbose_name_plural': 'IP 白名单',
                'db_table': 'account_ip_whitelist',
            },
        ),
        migrations.CreateModel(
            name='PaidChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '付费章节',
                'verbose_name_plural': '付费章节',
                'db_table': 'account_paid_chapter',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='订单号')),
                ('product_type', models.CharField(choices=[('vip_monthly', 'VIP月卡'), ('vip_yearly', 'VIP年卡'), ('coins', '金币充值'), ('chapter', '付费章节')], max_length=32, verbose_name='商品类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='货币')),
                ('provider', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('paypal', 'PayPal')], default='alipay', max_length=16, verbose_name='支付渠道')),
                ('provider_order_id', models.CharField(blank=True, max_length=128, verbose_name='渠道订单号')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '失败'), ('refunded', '已退款')], default='pending', max_length=16, verbose_name='状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('book_id', models.IntegerField(blank=True, null=True, verbose_name='书籍ID')),
                ('chapter_id', models.IntegerField(blank=True, null=True, verbose_name='章节ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'db_table': 'account_payment_order',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='权限码')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'account_permission',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ReaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('password_hash', models.CharField(blank=True, max_length=128, verbose_name='密码哈希')),
                ('nickname', models.CharField(blank=True, max_length=64, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('membership_level', models.CharField(choices=[('free', '免费'), ('vip', 'VIP'), ('premium', '高级')], default='free', max_length=16, verbose_name='会员等级')),
                ('membership_expires', models.DateTimeField(blank=True, null=True, verbose_name='会员到期')),
                ('coins', models.IntegerField(default=0, help_text='用于付费章节', verbose_name='金币')),
                ('reading_font', models.CharField(default='serif', max_length=32, verbose_name='阅读字体')),
                ('reading_size', models.IntegerField(default=18, verbose_name='阅读字号')),
                ('night_mode', models.BooleanField(default=False, verbose_name='夜间模式')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '读者账户',
                'verbose_name_plural': '读者账户',
                'db_table': 'account_reader_profile',
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_order', models.IntegerField(default=1, verbose_name='章节序号')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('read_duration', models.IntegerField(default=0, verbose_name='阅读时长(秒)')),
            ],
            options={
                'verbose_name': '阅读历史',
                'verbose_name_plural': '阅读历史',
                'db_table': 'account_reading_history',
                'ordering': ('-read_at',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色名')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='角色代码')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, help_text='系统内置角色不可删除', verbose_name='系统内置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='account.permission')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'account_role',
                'ordering': ('name',),
            },
        ),
    ]
