# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('novel', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinghistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.book'),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.chapter'),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='account.readerprofile'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.readerprofile'),
        ),
        migrations.AddField(
            model_name='paidchapter',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.chapter'),
        ),
        migrations.AddField(
            model_name='paidchapter',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.paymentorder'),
        ),
        migrations.AddField(
            model_name='paidchapter',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_chapters', to='account.readerprofile'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.book'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf', to='account.readerprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='account.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['reader', '-read_at'], name='account_rea_reader__ae6b28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paidchapter',
            unique_together={('reader', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='bookshelf',
            unique_together={('reader', 'book')},
        ),
    ]
