# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, unique=True, verbose_name='敏感词')),
                ('category', models.CharField(choices=[('general', '通用'), ('political', '政治'), ('adult', '成人'), ('violence', '暴力')], default='general', max_length=32, verbose_name='分类')),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=16, verbose_name='严重度')),
                ('replacement', models.CharField(blank=True, default='***', max_length=128, verbose_name='替换为')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词',
                'db_table': 'cleaner_banned_keyword',
            },
        ),
        migrations.CreateModel(
            name='CleaningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='规则名')),
                ('target', models.CharField(choices=[('chapter', '章节正文'), ('book', '书籍简介'), ('author', '作者简介'), ('all', '全部')], default='chapter', max_length=16, verbose_name='目标')),
                ('strategy', models.CharField(choices=[('regex', '正则替换'), ('css_remove', 'CSS 移除'), ('xpath_remove', 'XPath 移除'), ('string_remove', '字符串移除'), ('string_replace', '字符串替换')], max_length=16, verbose_name='策略')),
                ('pattern', models.TextField(verbose_name='匹配模式')),
                ('replacement', models.TextField(blank=True, default='', verbose_name='替换为')),
                ('priority', models.IntegerField(default=100, verbose_name='优先级')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '清洗规则',
                'verbose_name_plural': '清洗规则',
                'db_table': 'cleaner_rule',
                'ordering': ('priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CleaningExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=16, verbose_name='目标类型')),
                ('target_id', models.IntegerField(verbose_name='目标ID')),
                ('before_size', models.IntegerField(default=0)),
                ('after_size', models.IntegerField(default=0)),
                ('changed', models.BooleanField(default=False, verbose_name='是否修改')),
                ('diff_summary', models.TextField(blank=True, verbose_name='变更摘要')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_cleaner.cleaningrule')),
            ],
            options={
                'verbose_name': '清洗记录',
                'verbose_name_plural': '清洗记录',
                'db_table': 'cleaner_execution',
                'ordering': ('-executed_at',),
            },
        ),
    ]
