# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='便于识别，例：北京-1', max_length=64, verbose_name='名称')),
                ('url', models.CharField(help_text='例：http://user:pass@ip:port 或 socks5://ip:port', max_length=255, verbose_name='代理URL')),
                ('proxy_type', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks5', 'SOCKS5')], default='http', max_length=8, verbose_name='类型')),
                ('region', models.CharField(blank=True, help_text='例：北京 / 上海', max_length=64, verbose_name='地区')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('priority', models.IntegerField(default=100, verbose_name='优先级')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('failure_count', models.IntegerField(default=0, verbose_name='失败次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='最近检测')),
                ('last_check_ok', models.BooleanField(blank=True, null=True, verbose_name='最近检测')),
                ('auto_disable_enabled', models.BooleanField(default=True, verbose_name='启用自动剔除')),
                ('min_success_rate', models.FloatField(default=0.3, help_text='当成功率低于此值时自动剔除（0.0~1.0）', verbose_name='最低成功率阈值')),
                ('min_sample_count', models.IntegerField(default=5, help_text='成功+失败次数累计达到此值后才参与剔除判断', verbose_name='最少统计样本数')),
                ('auto_disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='自动剔除时间')),
                ('auto_disabled_reason', models.CharField(blank=True, max_length=255, verbose_name='剔除原因')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '代理池',
                'verbose_name_plural': '代理池',
                'db_table': 'crawler_proxy_pool',
                'ordering': ('-priority', 'id'),
            },
        ),
    ]
