# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='模板名')),
                ('output_format', models.CharField(choices=[('txt', 'TXT'), ('epub', 'EPUB')], default='txt', max_length=8, verbose_name='输出格式')),
                ('chapter_header', models.TextField(blank=True, default='', verbose_name='章节头部插入')),
                ('chapter_footer', models.TextField(blank=True, default='', verbose_name='章节尾部插入')),
                ('book_preface', models.TextField(blank=True, default='', verbose_name='前言插入')),
                ('book_afterword', models.TextField(blank=True, default='', verbose_name='后记插入')),
                ('site_info_block', models.TextField(blank=True, default='', verbose_name='站点信息块')),
                ('ad_block', models.TextField(blank=True, default='', verbose_name='广告块')),
                ('enable_confusion', models.BooleanField(default=False, verbose_name='启用混淆')),
                ('confusion_density', models.FloatField(default=0.01, help_text='0.001~0.05 推荐范围', verbose_name='混淆密度')),
                ('confusion_chars', models.TextField(blank=True, default='\u200b\u200c\u200d\ufeff', verbose_name='混淆字符集')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '下载模板',
                'verbose_name_plural': '下载模板',
                'db_table': 'download_template',
            },
        ),
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_format', models.CharField(max_length=8, verbose_name='格式')),
                ('file_path', models.CharField(max_length=512, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('chapters_count', models.IntegerField(default=0, verbose_name='章节数')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='novel.book')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_download.downloadtemplate')),
            ],
            options={
                'verbose_name': '下载记录',
                'verbose_name_plural': '下载记录',
                'db_table': 'download_record',
                'ordering': ('-id',),
            },
        ),
    ]
