# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='作者名')),
                ('alias', models.JSONField(blank=True, default=list, verbose_name='作者别名')),
                ('source_url', models.URLField(blank=True, verbose_name='作者页地址')),
                ('intro', models.TextField(blank=True, verbose_name='作者简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'novel_author',
                'unique_together': {('name', 'source_url')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='书名')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL别名')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='uploads/covers/%Y/%m/', verbose_name='封面图')),
                ('cover_url', models.URLField(blank=True, verbose_name='原始封面URL')),
                ('intro', models.TextField(blank=True, verbose_name='简介')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='关键词')),
                ('word_count', models.BigIntegerField(default=0, verbose_name='字数')),
                ('chapter_count', models.IntegerField(default=0, verbose_name='章节数')),
                ('volume_count', models.IntegerField(default=0, help_text='自动计算', verbose_name='分卷数')),
                ('status', models.CharField(choices=[('ongoing', '连载中'), ('completed', '已完结'), ('unknown', '未知')], default='ongoing', max_length=16, verbose_name='状态')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完结时间')),
                ('last_chapter_title', models.CharField(blank=True, max_length=255, verbose_name='最新章节标题')),
                ('rating', models.FloatField(default=0, verbose_name='评分')),
                ('view_count', models.BigIntegerField(default=0, verbose_name='浏览量')),
                ('source_site', models.CharField(blank=True, max_length=255, verbose_name='采集源域名')),
                ('source_url', models.URLField(blank=True, db_index=True, verbose_name='源书籍页URL')),
                ('source_book_id', models.CharField(blank=True, max_length=128, verbose_name='源书籍ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='novel.author')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'novel_book',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('order_index', models.IntegerField(db_index=True, verbose_name='排序')),
                ('source_order', models.IntegerField(default=0, verbose_name='原始排序')),
                ('disorder_applied', models.BooleanField(default=False, verbose_name='乱序重排')),
                ('content', models.TextField(blank=True, verbose_name='正文')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('source_url', models.URLField(blank=True, verbose_name='源章节URL')),
                ('source_id', models.CharField(blank=True, max_length=128, verbose_name='源章节ID')),
                ('source_paged', models.BooleanField(default=False, verbose_name='是否分页')),
                ('source_page_count', models.IntegerField(default=1, verbose_name='分页数')),
                ('status', models.CharField(choices=[('pending', '待采集'), ('fetched', '已采集'), ('cleaned', '已清洗'), ('published', '已发布'), ('error', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('error_msg', models.TextField(blank=True, verbose_name='错误信息')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='采集时间')),
                ('txt_path', models.CharField(blank=True, max_length=512, verbose_name='TXT路径')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novel.book')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 'novel_chapter',
                'ordering': ('order_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='标签')),
                ('is_auto', models.BooleanField(default=False, verbose_name='自动生成')),
                ('suggest_source', models.CharField(blank=True, max_length=64, verbose_name='来源建议词')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'novel_tag',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例：第一卷 初出茅庐', max_length=128, verbose_name='卷名')),
                ('intro', models.TextField(blank=True, verbose_name='卷简介')),
                ('order_index', models.IntegerField(db_index=True, default=0, help_text='第几卷，从 1 开始', verbose_name='卷序号')),
                ('source_id', models.CharField(blank=True, max_length=128, verbose_name='源分卷ID')),
                ('chapter_count', models.IntegerField(default=0, verbose_name='章节计数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='novel.book')),
            ],
            options={
                'verbose_name': '分卷',
                'verbose_name_plural': '分卷',
                'db_table': 'novel_volume',
                'ordering': ('order_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SuggestKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=128, verbose_name='关键词')),
                ('main_slug', models.SlugField(max_length=255, verbose_name='主书籍slug')),
                ('source', models.CharField(max_length=32, verbose_name='来源引擎')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggest_keywords', to='novel.book')),
            ],
            options={
                'verbose_name': '搜索引擎建议词',
                'verbose_name_plural': '搜索引擎建议词',
                'db_table': 'novel_suggest_keyword',
            },
        ),
        migrations.CreateModel(
            name='ChapterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('is_spoiler', models.BooleanField(default=False, verbose_name='剧透标记')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='novel.chapter')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='novel.chaptercomment')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='account.readerprofile')),
            ],
            options={
                'verbose_name': '章节评论',
                'verbose_name_plural': '章节评论',
                'db_table': 'novel_chapter_comment',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(blank=True, help_text='所属分卷', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='novel.volume'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='分类名')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='别名')),
                ('cover', models.URLField(blank=True, verbose_name='分类封面')),
                ('intro', models.TextField(blank=True, verbose_name='简介')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='novel.category')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'novel_category',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='1-5 星', verbose_name='评分')),
                ('review', models.TextField(blank=True, max_length=500, verbose_name='书评')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='novel.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='account.readerprofile')),
            ],
            options={
                'verbose_name': '书籍评分',
                'verbose_name_plural': '书籍评分',
                'db_table': 'novel_book_rating',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='novel.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='novel.tag'),
        ),
        migrations.AddIndex(
            model_name='volume',
            index=models.Index(fields=['book', 'order_index'], name='novel_volum_book_id_3133e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('book', 'order_index'), ('book', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='suggestkeyword',
            unique_together={('keyword', 'source')},
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['book', 'status'], name='novel_chapt_book_id_c17401_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['book', 'order_index'], name='novel_chapt_book_id_520493_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('book', 'source_url'), ('book', 'title', 'order_index')},
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('reader', 'book')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status', 'is_published'], name='novel_book_status_27499c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='novel_book_created_a97a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', 'status'], name='novel_book_author__ff0881_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug', 'is_published'], name='novel_book_slug_148739_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-rating'], name='novel_book_rating_29a47a_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-updated_at'], name='novel_book_updated_19d10f_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['source_site', 'is_deleted'], name='novel_book_source__3f7917_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['finished_at'], name='novel_book_finishe_2827b3_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status', 'is_published', '-rating'], name='book_status_rating_idx'),
        ),
    ]
