# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('host', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='域名')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('anti_detection', models.JSONField(blank=True, default=dict, verbose_name='反反爬配置')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '采集源',
                'verbose_name_plural': '采集源',
                'db_table': 'crawler_source',
            },
        ),
        migrations.CreateModel(
            name='CrawlerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='规则名')),
                ('target', models.CharField(choices=[('list', '列表页'), ('book', '书籍信息页'), ('toc', '章节目录页'), ('chapter', '章节内容页')], db_index=True, max_length=16, verbose_name='目标类型')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('priority', models.IntegerField(default=100, verbose_name='优先级')),
                ('config', models.JSONField(default=dict, verbose_name='规则配置')),
                ('last_test_html', models.TextField(blank=True, verbose_name='最近测试HTML')),
                ('last_test_result', models.JSONField(blank=True, default=dict, verbose_name='最近测试结果')),
                ('last_test_at', models.DateTimeField(blank=True, null=True, verbose_name='最近测试时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='crawler_rules.crawlersource')),
            ],
            options={
                'verbose_name': '采集规则',
                'verbose_name_plural': '采集规则',
                'db_table': 'crawler_rule',
                'ordering': ('priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('config_snapshot', models.JSONField(verbose_name='配置快照')),
                ('changed_by', models.CharField(blank=True, max_length=64, verbose_name='修改人')),
                ('change_reason', models.CharField(blank=True, max_length=255, verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='crawler_rules.crawlerrule')),
            ],
            options={
                'verbose_name': '规则版本',
                'verbose_name_plural': '规则版本',
                'db_table': 'crawler_rule_version',
                'ordering': ('-version_number',),
                'indexes': [models.Index(fields=['rule', '-version_number'], name='crawler_rul_rule_id_8eb668_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='crawlerrule',
            index=models.Index(fields=['source', 'target', 'enabled'], name='crawler_rul_source__7052c9_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlerrule',
            index=models.Index(fields=['target'], name='crawler_rul_target_de8deb_idx'),
        ),
    ]
