# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='用户名')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '退出'), ('view', '查看'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('run', '执行'), ('pause', '暂停'), ('stop', '停止'), ('export', '导出'), ('upload', '上传'), ('download', '下载')], db_index=True, max_length=16, verbose_name='动作')),
                ('resource', models.CharField(blank=True, help_text="如 'book'/'rule'/'task'", max_length=64, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, max_length=64, verbose_name='资源ID')),
                ('method', models.CharField(blank=True, max_length=8, verbose_name='HTTP 方法')),
                ('path', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='路径')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='UA')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='请求体的关键信息（不含密码/敏感字段）', verbose_name='载荷')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP 状态码')),
                ('success', models.BooleanField(default=True, verbose_name='成功')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_log',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['user_id', 'action', 'created_at'], name='audit_log_user_id_7b1d88_idx'), models.Index(fields=['resource', 'resource_id', 'created_at'], name='audit_log_resourc_17283b_idx')],
            },
        ),
    ]
