# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='规则名')),
                ('pattern', models.CharField(help_text='应用到标题/简介/最近章节标题', max_length=255, verbose_name='正则')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('priority', models.IntegerField(default=100, verbose_name='优先级')),
                ('hit_count', models.IntegerField(default=0, verbose_name='命中次数')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True, verbose_name='最近命中')),
            ],
            options={
                'verbose_name': '完结规则',
                'verbose_name_plural': '完结规则',
                'db_table': 'classifier_finished_pattern',
                'ordering': ('priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CategoryKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=64, verbose_name='分类名')),
                ('keyword', models.CharField(db_index=True, max_length=64, verbose_name='关键词')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重')),
                ('hit_count', models.IntegerField(default=0, verbose_name='命中次数')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True, verbose_name='最近命中')),
                ('last_hit_book_id', models.IntegerField(blank=True, null=True, verbose_name='最近命中书籍ID')),
            ],
            options={
                'verbose_name': '分类关键词',
                'verbose_name_plural': '分类关键词',
                'db_table': 'classifier_category_keyword',
                'unique_together': {('category_name', 'keyword')},
            },
        ),
    ]
