# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('provider', models.CharField(choices=[('dingtalk', '钉钉'), ('wecom', '企业微信'), ('slack', 'Slack'), ('generic', '通用 HTTP POST'), ('email', '邮件 (SMTP)')], default='dingtalk', max_length=16, verbose_name='类型')),
                ('url', models.URLField(blank=True, help_text='钉钉/企业微信机器人 webhook URL', max_length=500, verbose_name='URL')),
                ('secret', models.CharField(blank=True, help_text='钉钉机器人加签密钥（可选）', max_length=128, verbose_name='加签密钥')),
                ('email_to', models.TextField(blank=True, help_text='邮件用，逗号分隔', verbose_name='收件人')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('events', models.JSONField(default=list, help_text='例 ["task.done","task.error","download.ready"]', verbose_name='订阅事件')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_count', models.IntegerField(default=0, verbose_name='发送次数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败次数')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='最近发送')),
                ('last_error', models.TextField(blank=True, verbose_name='最近错误')),
            ],
            options={
                'verbose_name': 'Webhook 端点',
                'verbose_name_plural': 'Webhook 端点',
                'db_table': 'webhook_endpoint',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=64, verbose_name='事件类型')),
                ('payload', models.JSONField(verbose_name='载荷')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP 状态码')),
                ('response_text', models.TextField(blank=True, verbose_name='响应内容')),
                ('success', models.BooleanField(default=False, verbose_name='成功')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook 投递记录',
                'verbose_name_plural': 'Webhook 投递记录',
                'db_table': 'webhook_delivery',
                'ordering': ('-sent_at',),
                'indexes': [models.Index(fields=['endpoint', 'event', 'sent_at'], name='webhook_del_endpoin_2d2a39_idx')],
            },
        ),
    ]
