# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('simple_reading', '简约阅读'), ('classic_shelf', '古典书架'), ('magazine_modern', '杂志现代'), ('dark_tech', '暗黑科技'), ('minimal_rank', '极简榜单')], max_length=32, unique=True, verbose_name='代码')),
                ('name', models.CharField(max_length=64, verbose_name='主题名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('preview', models.URLField(blank=True, verbose_name='预览图URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('config_schema', models.JSONField(blank=True, default=dict, verbose_name='配置 schema')),
                ('default_config', models.JSONField(blank=True, default=dict, verbose_name='默认配置')),
            ],
            options={
                'verbose_name': '主题模板',
                'verbose_name_plural': '主题模板',
                'db_table': 'sites_theme',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='域名')),
                ('name', models.CharField(max_length=128, verbose_name='站名')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('site_title', models.CharField(max_length=255, verbose_name='首页标题')),
                ('site_description', models.TextField(blank=True, verbose_name='首页描述')),
                ('site_keywords', models.CharField(blank=True, max_length=255, verbose_name='首页关键词')),
                ('logo', models.URLField(blank=True, verbose_name='Logo URL')),
                ('favicon', models.URLField(blank=True, verbose_name='Favicon URL')),
                ('robots_txt', models.TextField(blank=True, verbose_name='robots.txt')),
                ('sitemap_enabled', models.BooleanField(default=True, verbose_name='Sitemap')),
                ('geo_region', models.CharField(blank=True, max_length=64, verbose_name='GEO地区')),
                ('geo_lang', models.CharField(default='zh-CN', max_length=16, verbose_name='GEO语言')),
                ('canonical_domain', models.CharField(blank=True, max_length=255, verbose_name='canonical 域名')),
                ('offset', models.IntegerField(default=0, help_text='书籍列表起始位置，避免站间内容完全重复', verbose_name='偏移量')),
                ('theme_config', models.JSONField(blank=True, default=dict, verbose_name='主题配置')),
                ('head_inject', models.TextField(blank=True, help_text='在 <head> 末尾注入', verbose_name='Head 注入代码')),
                ('body_inject', models.TextField(blank=True, help_text='在 </body> 前注入', verbose_name='Body 注入代码')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='sites.theme')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'db_table': 'sites_site',
                'ordering': ('host',),
            },
        ),
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='广告位名')),
                ('slot_type', models.CharField(choices=[('header_banner', '顶部横幅'), ('sidebar', '侧边栏'), ('footer_banner', '底部横幅'), ('chapter_top', '章节顶部'), ('chapter_bottom', '章节底部'), ('list_between', '列表中间'), ('popup', '弹窗')], default='header_banner', max_length=32, verbose_name='位置')),
                ('ad_format', models.CharField(choices=[('html', 'HTML 代码'), ('image', '图片'), ('text', '纯文本'), ('adsense', 'Google AdSense')], default='html', max_length=16, verbose_name='格式')),
                ('content', models.TextField(blank=True, help_text='HTML 代码 / 图片 URL / 文本 / AdSense 代码', verbose_name='广告内容')),
                ('image_url', models.URLField(blank=True, verbose_name='图片URL')),
                ('link_url', models.URLField(blank=True, verbose_name='跳转链接')),
                ('width', models.IntegerField(default=0, help_text='0=自适应', verbose_name='宽度(px)')),
                ('height', models.IntegerField(default=0, help_text='0=自适应', verbose_name='高度(px)')),
                ('theme', models.CharField(blank=True, help_text='留空=所有主题', max_length=32, verbose_name='适用主题')),
                ('page_types', models.JSONField(default=list, help_text='["home","book","chapter"]', verbose_name='页面类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('display_probability', models.FloatField(default=1.0, help_text='0.0-1.0', verbose_name='展示概率')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('impression_count', models.BigIntegerField(default=0, verbose_name='展示次数')),
                ('click_count', models.BigIntegerField(default=0, verbose_name='点击次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_slots', to='sites.site')),
            ],
            options={
                'verbose_name': '广告位',
                'verbose_name_plural': '广告位',
                'db_table': 'sites_ad_slot',
                'ordering': ('slot_type', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ABTestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_ratio', models.FloatField(default=0.5, help_text='0.0-1.0，A 主题的比例', verbose_name='A/B 分流比例')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_a', models.IntegerField(default=0, verbose_name='A 主题浏览')),
                ('views_b', models.IntegerField(default=0, verbose_name='B 主题浏览')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='sites.site')),
                ('theme_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests_a', to='sites.theme')),
                ('theme_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests_b', to='sites.theme')),
            ],
            options={
                'verbose_name': 'A/B 测试',
                'verbose_name_plural': 'A/B 测试',
                'db_table': 'sites_ab_test',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, max_length=255, verbose_name='域名')),
                ('page_type', models.CharField(choices=[('home', '首页'), ('book', '书籍页'), ('chapter', '章节页'), ('category', '分类页'), ('search', '搜索页')], max_length=32, verbose_name='页面类型')),
                ('path', models.CharField(max_length=255, verbose_name='路径')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='UA')),
                ('referer', models.CharField(blank=True, max_length=255, verbose_name='来源')),
                ('response_ms', models.IntegerField(default=0, verbose_name='响应时间(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='sites.site')),
            ],
            options={
                'verbose_name': '页面浏览',
                'verbose_name_plural': '页面浏览',
                'db_table': 'sites_page_view',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['host', 'page_type', '-created_at'], name='sites_page__host_f7861d_idx')],
            },
        ),
    ]
