# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crawler_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='任务名')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('target_urls', models.JSONField(default=list, help_text='单本/多本URL数组', verbose_name='目标URL列表')),
                ('url_range', models.JSONField(blank=True, default=dict, help_text='支持分页范围 / 章节范围，例 {start:1,end:100,step:1}', verbose_name='URL范围配置')),
                ('mode', models.CharField(choices=[('full', '完全覆盖'), ('incremental', '增量更新')], default='full', max_length=16, verbose_name='模式')),
                ('threads_min', models.IntegerField(default=2, verbose_name='最小线程')),
                ('threads_max', models.IntegerField(default=5, verbose_name='最大线程')),
                ('interval_min', models.FloatField(default=1.0, verbose_name='最小间隔(秒)')),
                ('interval_max', models.FloatField(default=3.0, verbose_name='最大间隔(秒)')),
                ('content_storage', models.CharField(choices=[('db', '数据库'), ('txt', 'TXT文件'), ('both', '两者')], default='db', max_length=8, verbose_name='章节内容存储方式')),
                ('cover_format', models.CharField(default='webp', max_length=8, verbose_name='封面格式')),
                ('download_cover', models.BooleanField(default=True, verbose_name='下载封面')),
                ('enable_disorder', models.BooleanField(default=False, verbose_name='章节乱序重排')),
                ('enable_dedup_by_url', models.BooleanField(default=True, verbose_name='按URL去重')),
                ('enable_dedup_by_title', models.BooleanField(default=False, verbose_name='按章节名去重')),
                ('enable_cleaner', models.BooleanField(default=True, verbose_name='启用内容清洗')),
                ('enable_classifier', models.BooleanField(default=True, verbose_name='启用智能分类')),
                ('enable_finished_detection', models.BooleanField(default=True, verbose_name='完结检测')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('queued', '已入队'), ('running', '运行中'), ('paused', '已暂停'), ('stopped', '已停止'), ('done', '完成'), ('error', '失败')], default='draft', max_length=16, verbose_name='状态')),
                ('celery_task_id', models.CharField(blank=True, max_length=128, verbose_name='Celery Task ID')),
                ('schedule_enabled', models.BooleanField(default=False, verbose_name='启用定时调度')),
                ('schedule_cron', models.CharField(blank=True, default='', help_text="标准 5 段 cron：minute hour day-of-month month day-of-week。例：'0 3 * * *' = 每天 3 点", max_length=128, verbose_name='Cron 表达式')),
                ('schedule_next_run', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('schedule_last_run', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('schedule_max_runs', models.IntegerField(default=0, help_text='0 = 无限', verbose_name='最大执行次数')),
                ('schedule_run_count', models.IntegerField(default=0, verbose_name='已执行次数')),
                ('priority', models.IntegerField(default=50, help_text='0-100，100 最高。高优先级任务会先获得执行槽位', verbose_name='任务优先级')),
                ('max_concurrent_per_class', models.IntegerField(default=3, help_text='同一 source 站点的任务最多同时运行 N 个。0 = 不限制', verbose_name='同类任务最大并发数')),
                ('exclusive', models.BooleanField(default=False, help_text='为 True 时，本任务运行期间不允许其他任务运行（适合大型全量采集）', verbose_name='独占执行')),
                ('retry_max', models.IntegerField(default=3, help_text='任务整体失败时的重试上限（0=不重试）', verbose_name='最大重试次数')),
                ('retry_delay', models.FloatField(default=60, help_text='每次重试前等待秒数', verbose_name='重试间隔(秒)')),
                ('retry_backoff', models.FloatField(default=2.0, help_text='每次重试间隔在上一次基础上乘以这个倍数', verbose_name='重试退避倍数')),
                ('retry_strategy', models.CharField(choices=[('always', '总是重试'), ('error_aware', '按错误类型判定'), ('never', '从不重试')], default='error_aware', help_text='error_aware: 对验证码/限流类错误重试，对内容缺失类不重试', max_length=32, verbose_name='重试策略')),
                ('retry_count', models.IntegerField(default=0, verbose_name='已重试次数')),
                ('retry_history', models.JSONField(blank=True, default=list, help_text='[{"attempt":1, "error":"...", "ts":"..."}]', verbose_name='重试历史')),
                ('trigger_on_dependency', models.BooleanField(default=False, help_text='为 True 时，depends_on 任务完成后会自动触发本任务', verbose_name='启用依赖触发')),
                ('trigger_condition', models.CharField(choices=[('success', '成功'), ('failure', '失败'), ('either', '成功或失败')], default='success', help_text='前置任务满足此条件才触发', max_length=16, verbose_name='触发条件')),
                ('total_items', models.IntegerField(default=0, verbose_name='总数')),
                ('processed_items', models.IntegerField(default=0, verbose_name='已处理')),
                ('success_items', models.IntegerField(default=0, verbose_name='成功')),
                ('failed_items', models.IntegerField(default=0, verbose_name='失败')),
                ('skipped_items', models.IntegerField(default=0, verbose_name='跳过')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('last_error', models.TextField(blank=True, verbose_name='最近错误')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_rule', models.ForeignKey(blank=True, limit_choices_to={'target': 'book'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_as_book', to='crawler_rules.crawlerrule')),
                ('chapter_rule', models.ForeignKey(blank=True, limit_choices_to={'target': 'chapter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_as_chapter', to='crawler_rules.crawlerrule')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawler_tasks', to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ForeignKey(blank=True, help_text='本任务会在前置任务成功完成后自动触发', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_tasks', to='crawler_tasks.crawlertask')),
                ('list_rule', models.ForeignKey(blank=True, limit_choices_to={'target': 'list'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_as_list', to='crawler_rules.crawlerrule')),
                ('toc_rule', models.ForeignKey(blank=True, limit_choices_to={'target': 'toc'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_as_toc', to='crawler_rules.crawlerrule')),
            ],
            options={
                'verbose_name': '采集任务',
                'verbose_name_plural': '采集任务',
                'db_table': 'crawler_task',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='模板名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('config', models.JSONField(default=dict, help_text='任务字段快照，用于创建新任务', verbose_name='配置')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='内置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '任务模板',
                'verbose_name_plural': '任务模板',
                'db_table': 'crawler_task_template',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CrawlerTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=8, verbose_name='级别')),
                ('message', models.TextField(verbose_name='日志内容')),
                ('url', models.URLField(blank=True, verbose_name='相关URL')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crawler_tasks.crawlertask')),
            ],
            options={
                'verbose_name': '采集任务日志',
                'verbose_name_plural': '采集任务日志',
                'db_table': 'crawler_task_log',
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='crawlertask',
            index=models.Index(fields=['status', 'enabled'], name='crawler_tas_status_97dfda_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlertask',
            index=models.Index(fields=['created_at'], name='crawler_tas_created_6b4fbc_idx'),
        ),
    ]
