# Generated by Django 4.2.16 on 2026-09-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterferenceSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='句子内容')),
                ('category', models.CharField(default='general', help_text='general / scene / dialogue / narration', max_length=32, verbose_name='分类')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('used_count', models.IntegerField(default=0, verbose_name='已用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '干扰句',
                'verbose_name_plural': '干扰句',
                'db_table': 'obfuscator_interference',
                'ordering': ('-weight', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=64, verbose_name='原词')),
                ('synonyms', models.JSONField(default=list, help_text='["替换词1","替换词2"]', verbose_name='同义词列表')),
                ('category', models.CharField(blank=True, default='general', help_text='general / verb / noun / adj / adv', max_length=32, verbose_name='分类')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '同义词',
                'verbose_name_plural': '同义词',
                'db_table': 'obfuscator_synonym',
                'unique_together': {('word', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ObfuscationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用混淆')),
                ('html_class_randomize', models.BooleanField(default=True, help_text='每次渲染生成随机 class 名映射', verbose_name='类名随机化')),
                ('html_attr_order_shuffle', models.BooleanField(default=True, verbose_name='属性顺序随机')),
                ('html_whitespace_noise', models.BooleanField(default=True, help_text='随机插入 HTML 注释 / 空白字符', verbose_name='空白噪声')),
                ('html_invisible_elements', models.BooleanField(default=True, help_text='随机插入 display:none 的 div/span', verbose_name='隐形元素')),
                ('html_comment_inject', models.BooleanField(default=True, help_text='随机插入 HTML 注释片段', verbose_name='注释噪声')),
                ('transcode_full_width', models.BooleanField(default=False, help_text='随机将半角字符转为全角（视觉相同，字节不同）', verbose_name='半角→全角')),
                ('transcode_homoglyph', models.BooleanField(default=False, help_text='替换拉丁字母为西里尔字母等 Unicode 同形字符', verbose_name='同形字替换')),
                ('transcode_zero_width', models.BooleanField(default=False, help_text='在字符间随机插入零宽字符（ZWS / ZWNJ 等）', verbose_name='零宽字符')),
                ('transcode_punctuation', models.BooleanField(default=True, help_text='标点符号替换为 Unicode 等价变体', verbose_name='标点变体')),
                ('transcode_density', models.FloatField(default=0.15, help_text='0.0~1.0，每个字符被转码的概率', verbose_name='转码密度')),
                ('rewrite_synonym', models.BooleanField(default=False, help_text='根据同义词词典随机替换', verbose_name='同义词替换')),
                ('rewrite_sentence_reorder', models.BooleanField(default=False, help_text='前后子句互换、副词位置调整', verbose_name='句型重排')),
                ('rewrite_interference', models.BooleanField(default=False, help_text='在每个段落尾部插入一句干扰句子', verbose_name='干扰句插入')),
                ('rewrite_interference_density', models.FloatField(default=0.3, help_text='0.0~1.0，每个段落插入干扰句的概率', verbose_name='干扰句密度')),
                ('cache_seconds', models.IntegerField(default=0, help_text='0 = 不缓存（每次渲染都生成唯一结构），>0 = 缓存 N 秒', verbose_name='渲染缓存秒数')),
                ('seed_per_request', models.BooleanField(default=True, help_text='True: 每个请求生成不同结构；False: 同一站点固定结构（开发用）', verbose_name='每请求重新生成种子')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obfuscation_profile', to='sites.site')),
            ],
            options={
                'verbose_name': '混淆配置',
                'verbose_name_plural': '混淆配置',
                'db_table': 'obfuscator_profile',
            },
        ),
        migrations.CreateModel(
            name='RewriteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_hash', models.CharField(db_index=True, max_length=64, verbose_name='原文哈希')),
                ('rewritten_hash', models.CharField(db_index=True, max_length=64, verbose_name='重写哈希')),
                ('transformations', models.JSONField(default=list, help_text='["synonym:word1->word2", "reorder", "interference:id=12"]', verbose_name='使用的变换')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.book')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.chapter')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site')),
            ],
            options={
                'verbose_name': '重写记录',
                'verbose_name_plural': '重写记录',
                'db_table': 'obfuscator_rewrite_record',
                'indexes': [models.Index(fields=['original_hash', 'site'], name='obfuscator__origina_662c60_idx')],
            },
        ),
    ]
